<?php

namespace ContainerPQW8RxE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryServicesCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\QueryServicesCommand' shared autowired service.
     *
     * @return \App\Command\QueryServicesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/QueryServicesCommand.php';

        return $container->services['console.command.public_alias.App\\Command\\QueryServicesCommand'] = new \App\Command\QueryServicesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
