<?php

namespace Container6wqCVXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryServicesCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\QueryServicesCommand' shared autowired service.
     *
     * @return \App\Command\QueryServicesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/QueryServicesCommand.php';

        $container->privates['App\\Command\\QueryServicesCommand'] = $instance = new \App\Command\QueryServicesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:query-services');

        return $instance;
    }
}
