<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6wqCVXa\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6wqCVXa/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6wqCVXa.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6wqCVXa\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container6wqCVXa\App_KernelTestDebugContainer([
    'container.build_hash' => '6wqCVXa',
    'container.build_id' => '71d8dbf5',
    'container.build_time' => 1710373755,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6wqCVXa');
