<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWR5F0C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWR5F0C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWR5F0C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWR5F0C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFWR5F0C\App_KernelDevDebugContainer([
    'container.build_hash' => 'FWR5F0C',
    'container.build_id' => '53615098',
    'container.build_time' => 1710374932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWR5F0C');
